$tip = [tiPS.PowerShellTip]::new()
$tip.Id = 'PowerShellIsOpenSource'
$tip.CreatedDate = [DateTime]::Parse('2023-07-16')
$tip.Title = 'PowerShell is open source'
$tip.TipText = 'Did you know that PowerShell is open source? You can contribute to the project on GitHub.'
$tip.Example = 'Example code to demonstrate the tip.'
$tip.Urls = @('https://github.com/PowerShell/PowerShell')
$tip.MinPowerShellVersion = '0.0'
$tip.Tags = @()
